version: '3'

services:
###> doctrine/doctrine-bundle ###
  database:
    image: 'mysql:latest'
    container_name: db_refugieensecurite
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${USER_MDP}
      MYSQL_DATABASE: ${databaseName}
    ports:
      - '127.0.0.1:3306:3306'
    volumes:
      - db-data:/var/lib/mysql
###< doctrine/doctrine-bundle ###

  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin_refugieensecurite
    restart: always
    depends_on:
      - database
    ports:
      - '127.0.0.1:6742:80'
    environment:
      PMA_HOST: database

  maildev:
    image: maildev/maildev
    container_name: maildev_docker_refugieensecurite
    command: bin/maildev --web 80 --smtp 25 --hide-extensions STARTTLS
    ports:
      - "127.0.0.1:8081:80"
    restart: always

  www:
    #la clé build represente le dossier de pointage ou se trouve le dockerfile
    build: docker/php
    container_name: php_refugieensecurite
    restart: always
    ports:
      - '127.0.0.1:8641:80'
    volumes:
      - ./docker/php/vhosts:/etc/apache2/sites-enabled
      - ./:/var/www/refugiesensecurite

#  node-service:
#    build:
#      context: docker
#      dockerfile: nodeJs/Dockerfile
#    container_name: nodejs_refugieensecurite
#    restart: always
#    networks:
#      - prod
#    ports:
#      - 3000:3000
#    volumes:
#      - docker/front:/var/www/refugiesensecurite/front

  node:
    image: node:12-alpine
    working_dir: /var/www/refugiesensecurite
    container_name: nodejs_refugieensecurite
    restart: always
    volumes:
      - .:/var/www/refugiesensecurite
    command: sh -c 'yarn && yarn run encore prod'
    depends_on:
      - www


volumes:
###> doctrine/doctrine-bundle ###
  db-data:
###< doctrine/doctrine-bundle ###
