version: '3'

services:
###> doctrine/doctrine-bundle ###
  database:
    image: 'mysql:latest'
    container_name: db_refugieensecurite
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${USER_MDP}
      MYSQL_DATABASE: ${databaseName}
    ports:
      # To allow the host machine to access the ports below, modify the lines below.
      # For example, to allow the host to connect to port 3306 on the container, you would change
      # "3306" to "3306:3306". Where the first port is exposed to the host and the second is the container port.
      # See https://docs.docker.com/compose/compose-file/#ports for more information.
      - '127.0.0.1:3306:3306'
      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./docker/db/data:/var/lib/postgresql/data:rw
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - prod
###< doctrine/doctrine-bundle ###

  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin_refugieensecurite
    restart: always
    networks:
      - prod
    depends_on:
      - database
    ports:
      - '127.0.0.1:6742:80'
    environment:
      PMA_HOST: database

  maildev:
    image: maildev/maildev
    container_name: maildev_docker_refugieensecurite
    command: bin/maildev --web 80 --smtp 25 --hide-extensions STARTTLS
    ports:
      - "127.0.0.1:8081:80"
    restart: always
    networks:
      - prod

  www:
    #la clé build represente le dossier de pointage ou se trouve le dockerfile
    build: docker/php
    container_name: php_refugieensecurite
    restart: always
    networks:
      - prod
    ports:
      - '127.0.0.1:8641:80'
    volumes:
      - ./docker/php/vhosts:/etc/apache2/sites-enabled
      - ./:/var/www/refugiesensecurite

#  node-service:
#    build:
#      context: docker
#      dockerfile: nodeJs/Dockerfile
#    container_name: nodejs_refugieensecurite
#    restart: always
#    networks:
#      - prod
#    ports:
#      - 3000:3000
#    volumes:
#      - docker/front:/var/www/refugiesensecurite/front

  node:
    image: node:12-alpine
    working_dir: /var/www/refugiesensecurite
    container_name: nodejs_refugieensecurite
    restart: always
    volumes:
      - .:/var/www/refugiesensecurite
    command: sh -c 'yarn && yarn run encore prod'
    depends_on:
      - www


volumes:
###> doctrine/doctrine-bundle ###
  db-data:
###< doctrine/doctrine-bundle ###
networks:
  prod:
